name: Run SODA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │  ┌───────── hour (0 - 23)
    #        │  │ ┌───────── day of the month (1 - 31)
    #        │  │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: "0 8 * * 1" # Every Monday at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache heliopy data
      uses: actions/cache@v2
      with:
        path: ~/heliopy/data/spice
        # Bump this version number ot clear the heliopy spice cache
        key: 'v1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements.txt
    - name: Generate HTML
      run: |
        python run_soda.py
    - name: Deploy 🚀
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: pages
        folder: . # The folder the action should deploy.
    - name: Copy file to another repository
      env:
        ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      run: |
        cp index.html $HOME/index.html
        cd $HOME
        git config --global user.email "einsteinisbae@gmail.com"
        git config --global user.name "JonasSinjan"
        git config --global credential.helper cache
        git clone https://${{secrets.ACCESS_TOKEN}}@github.com/JonasSinjan/new_website.git target_repo
        cd target_repo/docs/projects/
        cp $HOME/index.html .
        mv index.html soda.md
        git add .
        git commit -m "push new md with html to projects"
        git push https://${{secrets.ACCESS_TOKEN}}@github.com/JonasSinjan/new_website.git HEAD:master